services:
  app:
    image: ghcr.io/icewheel-oss/icewheel-energy:latest
    container_name: icewheel-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8081}:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://icewheel-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TESLA_CLIENT_ID=${TESLA_CLIENT_ID}
      - TESLA_CLIENT_SECRET=${TESLA_CLIENT_SECRET}
      - TESLA_REDIRECT_URI=${TESLA_REDIRECT_URI}
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_PROTOCOL=${APP_PROTOCOL}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
    depends_on:
      - icewheel-db
    volumes:
      - ./icewheel-energy-data/config/application.yml:/app/resources/application.yml

  icewheel-db:
    image: postgres:16
    container_name: icewheel-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./icewheel-energy-data/postgres-data:/var/lib/postgresql/data
