name: Docker Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Get project version
      id: project
      run: echo "::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"

    - name: Build image
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=icewheel-energy:${{ steps.project.outputs.version }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag image
      run: |
        docker tag icewheel-energy:${{ steps.project.outputs.version }} ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker tag icewheel-energy:${{ steps.project.outputs.version }} ghcr.io/${{ github.repository }}:latest

    - name: Push image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:latest
