name: Docker Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Get project version
      id: project
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push amd64 image
      run: |
        mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64

    - name: Build and push arm64 image
      run: |
        mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64 -Dspring-boot.build-image.platform=linux/arm64
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64

    - name: Create and push manifest
      run: |
        docker manifest create ghcr.io/${{ github.repository }}:${{ github.sha }} --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64
        docker manifest push ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Create and push latest manifest
      run: |
        docker manifest create ghcr.io/${{ github.repository }}:latest --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64 --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64
        docker manifest push ghcr.io/${{ github.repository }}:latest